### PR TITLE
Update month names in croatian translation

### PR DESCRIPTION
**Pull request by tomhorvat**

### CODE REVIEW

**Comment by brunob** [comment]
Hi and thanks for the patch, you should use https://trad.spip.net/ for translations updates in order to get this properly merged with credits :)

Closgin the issue, but feel free to ask if you have any question about it.

**Comment by tomhorvat** [comment]
Is it possible to update through Github?

**Comment by brunob** [comment]
No, translations are handled through trad.spip.net website, tell me if you want me to do the changes for you from the website or if you prefer to do it by yourself.

**Comment by tomhorvat** [comment]
Since I'm not familiar with that workflow, please update changes. Thank you!

**Comment by brunob** [comment]
Done : https://trad.spip.net/tradlang_module/spip?lang_orig=fr&lang_cible=hr

**Pull request closed without merging**
